<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Jquery Ajax MVC</title>
    <link rel="stylesheet" href="app\views\assets\css\bootstrap.min.css">
    <link rel="stylesheet" href="app\views\assets\css\styles.css">
</head>
<body>
    
